### ISSUE TITLE
Question: Is there a way to disable some macros while printing

### ISSUE THREAD

**Issue by dushyantahuja** [cadriel/fluidd#10]
Just wanted to check - I have a few macros, that would create issues with prints if they are run while printing. Is there a way to tag macros so that they are disabled while printing.

**Comment by cadriel** [comment]
Not currently. I've had people suggest both scenarios whereby some want them disabled, versus not during a print.

I'll have a think about this. There are other enhancements to macros regarding organization and categorization - and that might be a good place to implement something like this against too.

**Comment by dushyantahuja** [comment]
Sounds good. Thanks for your great work. I had never thought that I could uninstall octoprint.

**Comment by cadriel** [comment]
No problem. :)

**Comment by cadriel** [comment]
Im going to close this for now, but improvements to macros and their display is on the list of improvements.. so watch out for a future release.
