### ISSUE TITLE
Tool widget layout misalignment on MBP 13

### ISSUE THREAD

**Issue by finelord** [cadriel/fluidd#102]
On MacBook Pro 13 (fullscreen, Chrome), Tools widget renders columns with controls as rows (v1.5.1-9db9322, it was fine on prev v1.4.x):
<img width="716" alt="Screen Shot 2021-01-17 at 8 59 28 PM" src="https://user-images.githubusercontent.com/1898278/104864936-88859b80-5908-11eb-982b-cbe3484cb938.png">

Adding 5px to its container fixes this:
![Screen Shot 2021-01-17 at 9 08 47 PM](https://user-images.githubusercontent.com/1898278/104864938-891e3200-5908-11eb-9622-b652a4cde88a.png)
<img width="707" alt="Screen Shot 2021-01-17 at 9 08 33 PM" src="https://user-images.githubusercontent.com/1898278/104864937-891e3200-5908-11eb-8c55-dc7d56962dec.png">

Columns layout is much more convenient, and 13' MBP resolution is pretty common I think. Worth fixing?

Feels like some inputs in the second column could be a bit narrower to compensate 5px.

**Comment by cadriel** [comment]
This'll be fixed in the next release. Thanks!
