### ISSUE TITLE
Infinityh NaNm NaNs in print timer

### ISSUE THREAD

**Issue by LazaroFilm** [cadriel/fluidd#11]
`0h 2m 22s / Infinityh NaNm NaNs` shows in the print timer section. 
My Pi is on the correct time zone (checked, and did a full reboot) 
This happens with any files made from SuperSlicer (have not tried other slicers) 
Mainsail is able to read the times properly. 

![Screen Shot 2020-10-22 at 4 16 22 PM](https://user-images.githubusercontent.com/18351100/96925455-31476a80-1482-11eb-8421-94b7678747b6.png)

**Comment by cadriel** [comment]
@LazaroFilm What estimations are you using? I.e., on the settings page - you have many options for choosing estimations, which one is set?

Also - if it is set to slicer, have you configured super slicer to send estimations?

Does the issue go away if you choose something other than slicer from the settings?

**Comment by LazaroFilm** [comment]
I'm using `Klipper estimations (accuracy over time)`
I have `Supports remaining times` selected in SuperSlicer
So I rotated through the settings and the NaN error disappeared from all settings (even the original setting) after that.
I'm currently in a print. I'll try to start the next print with a different Time setting to see if it does the same thing.

**Comment by cadriel** [comment]
I've added some extra checks here, can you please confirm and close with v0.0.9?

**Comment by LazaroFilm** [comment]
Just updated tonight. Will test tomorrow.

**Comment by LazaroFilm** [comment]
Still happening on v0.10 when Klipper is the time source. Other time sources are working fine.

**Comment by AlexGirardDev** [comment]
I have also been running into this issue since I want to say 0.06,

I am user SuperSlic3r as my slicer and have updated moonraker and fluidd to the latest versions

**Comment by cadriel** [comment]
Is it for any size print? Or super long ones?

**Comment by AlexGirardDev** [comment]
All sized prints, ranging from like 6 minutes to 40 hours.
I have attached a sample gcode from my slicer that repro's the issue on my end.

If you are unable to repro this yourself I can deploy some debug builds if you have them or I can also just try and reformatting my PI with a fresh install to since this problems seems to be a config issue at this point as it only effects a small nuber of people.



[left-plate.zip](https://github.com/cadriel/fluidd/files/5479282/left-plate.zip)

**Comment by cadriel** [comment]
I've tried with your gcode, and am unable to reproduce.

I'll have a deeper look into this over the next day or so and see if i can't spot anything obvious.

**Comment by cadriel** [comment]
Hrm, I don't suppose you guys are using Internet Explorer are you? If so - what version?

**Comment by cadriel** [comment]
Ok, I think I may have found a culprit.. 

Can you give this test build a shot and let me know how you get on?
[fluidd_v0.1.0_test.zip](https://github.com/cadriel/fluidd/files/5485448/fluidd_v0.1.0_test.zip)

**Comment by AlexGirardDev** [comment]
Yep this seems to have fixed the issue!


FWIW I am not using internet explorer lol.

Thanks for your awesome work @cadriel and tracking down this bug.

**Comment by cadriel** [comment]
Fantastic news! I'll merge the change, you can expect it officially in the next release. :)
