### ISSUE TITLE
Show cursor in graphs

### ISSUE THREAD

**Issue by dimalo** [cadriel/fluidd#112]
As a user I want to examine the temperature graphs and spot inaccuracies in order to improve printer control.
Doing that I want to know the temperature values as I spot wavy or bumpy temperature curves.

Having a cursor on the graph (pretty much like good-ol octoprint) would allow me to accomplish this.

**Comment by cadriel** [comment]
This will be in the next release.

**Comment by dimalo** [comment]
Love to see you chose echarts 👍🏻
