### ISSUE TITLE
Change and save color to printer instance

### ISSUE THREAD

**Issue by dimalo** [cadriel/fluidd#113]
As a user having multiple printers connected and managed through Fluidd, I would like to distinguish each printer not only by name, but also by color. 
This allows me to clearly tell the machines apart as I use the UI and prevent possible catastrophic events :)

I would like to configure a color next to the printer's name, which is then saved and further on used to colorize parts of the UI.
Even just the toolbar would already be a great enhancement!

**Comment by cadriel** [comment]
This is in place.
