### ISSUE TITLE
Print time estimate

### ISSUE THREAD

**Issue by nightwolfix** [cadriel/fluidd#114]
The print time estimate looks way off in most cases, even with the respect to what the slicer is estimating. Is there a plan to make this more accurate?

**Comment by dimalo** [comment]
If you use a slicer which is capable of writing time estimations to gcode like PrusaSlicer, you can switch to that one. made a good difference for me...

**Comment by cadriel** [comment]
Use slicer estimations, and - if supported, turn on m73.

Then in fluidd, select slicer for estimations.
