### ISSUE TITLE
Docker: warning about misconfigured update_manager

### ISSUE THREAD

**Issue by dimalo** [cadriel/fluidd#118]
![image](https://user-images.githubusercontent.com/26287094/105725446-41f7f880-5f29-11eb-8a96-b4459c93cdbf.png)

Just having set

[update_manager]

in moonraker.conf

Does fluidd expect client update_manager entries? I am using the default config.json

**Comment by dimalo** [comment]
Printer and moonraker are working fine though
Will have a look into the moonraker logs...

**Comment by cadriel** [comment]
This is not unique to Docker. It's telling you that one of your moonraker plugins is failing.

If you're using the latest docker (v1.6.1) then you need to make sure Klipper and Moonraker are up to date.

**Comment by dimalo** [comment]
They are up to date. Not sure why you're closing this - the issue is still there. I can change the title though...

**Comment by dimalo** [comment]
finally had the time to go through logs. yep a moonraker issue...

```confighelper.ConfigError: Invalid path for option 'python_dist_path'```
