### ISSUE TITLE
Console input field goes up based on the length of the console log

### ISSUE THREAD

**Issue by vladbabii** [cadriel/fluidd#12]
If there's no row, the "Send gcode" input and button are at the top of the area, if there area a couple of rows it goes down in the middle and once more than some amount of rows it behaves normally and sticks to bottom of the area. Image attached with the middle case..

![111215151](https://user-images.githubusercontent.com/4667916/96997548-9f4f6880-153a-11eb-99bb-ade7c31f13f1.JPG)

**Comment by cadriel** [comment]
This is fixed in mainline, please recheck for next release.
