### ISSUE TITLE
Print time / % keep intermittently showing and disappearing during a print

### ISSUE THREAD

**Issue by Nandox7** [cadriel/fluidd#121]
Hi,

I noticed that the stats for elapsed and remaining time keep showing and disappearing during the print.
Only the other values keep showing all the time.

![chrome_H1lVCzcXFB](https://user-images.githubusercontent.com/117827/106082361-78dd3280-6112-11eb-9942-45d5b2cd857e.png)

Don't know exactly who is responsible for that ata (Moonraker?) but I also have a LCD with KlipperScreen and the values
show all the time during the print.

**Comment by cadriel** [comment]
What estimates setting are you using?

**Comment by Nandox7** [comment]
I'm using "File estimation".

**Comment by cadriel** [comment]
I believe this is now resolved by way of the 1.6.3 commit. Please feel free to re-open if that is not the case.
