### ISSUE TITLE
MESH case issues

### ISSUE THREAD

**Issue by cadriel** [cadriel/fluidd#122]
Sounds like the UI can't distinguish between case, or something is otherwise up with the names of meshes.

**Comment by Cvshewnut** [comment]
21:44:07
$ BED_MESH_PROFILE LOAD=100c
21:44:07
!! bed_mesh: Unknown profile [100c]
21:44:31
$ BED_MESH_PROFILE LOAD=100c
21:44:31
!! bed_mesh: Unknown profile [100c]
21:44:35
$ BED_MESH_PROFILE LOAD=100C
21:44:51
$ BED_MESH_PROFILE LOAD=100c
21:44:52
!! bed_mesh: Unknown profile [100c]

**Comment by cadriel** [comment]
This should be resolved in the next release..
