### ISSUE TITLE
macros don't get executed if named in special way

### ISSUE THREAD

**Issue by Spacemarine2018** [cadriel/fluidd#124]
I needed a simple button, that moves the x-axis to 200. So I wrote:

[gcode_macro g1_x200]
gcode:
  g1 x200

However, this macro doesn't do anything and also shows no error. I can push the button, but nothing happens.
After I renamed it, it works:

[gcode_macro x200]
gcode:
  g1 x200

**Comment by cadriel** [comment]
Are you sure this is a fluidd issue? Did you try to run the g1_x200 macro from the console to confirm it worked there first?

**Comment by markwinger** [comment]
This is klipper.  The docs specify that the names can only have numbers at the end, not embedded in the middle.

**Comment by Spacemarine2018** [comment]
Sorry, this is my fault then, I wasn't aware of that restiction. However, I think it would be good for klipper to raise a warning in that case, but that's another problem.

Maybe fluidd can refuse to create macro buttons with wrong formatting?

**Comment by cadriel** [comment]
Really, it's up to moonraker / klipper to validate these. Fluidd only represents the data passed back to it from the API.
