### ISSUE TITLE
Printer Limits RED color

### ISSUE THREAD

**Issue by anteyru** [cadriel/fluidd#125]
1. Limits cannot be scaled in any mode.
fluidd last v1.6.1
moonraker last v0.2.8-52

2 Thermals Graph below the target temperature.

![2021-01-29_163359_172 16 0 105](https://user-images.githubusercontent.com/8513289/106281204-f2c70600-624f-11eb-8344-23d027d034e2.png)

**Comment by ReXT3D** [comment]
I had the same issue with a forked Klipper, see [Potential issue with some display elements when using recent Klipper commits](https://github.com/cadriel/fluidd/issues/126).  Are you using official Klipper build?

**Comment by cadriel** [comment]
The screenshots indicate you aren't running the latest klipper release. Please upgrade klipper, and the problem should go away.
