### ISSUE TITLE
Current layer value

### ISSUE THREAD

**Issue by Swift-Tester** [cadriel/fluidd#130]
Hello!

Please consider adding currently printing layer value.
Maybe right after "Z" in "Tool" widget.

Thanks in advance.

**Comment by cadriel** [comment]
There's no way to reliably do this because klipper and moonraker don't give us this value. Working it out based on layer height and total object height is unreliable due to prints being able to have many layer heights.

If this comes in klipper side, I'll implement it.

Thanks!

**Comment by maruhe** [comment]
how does mailsail know the layer and count?

![grafik](https://user-images.githubusercontent.com/49123648/122658686-8b631180-d170-11eb-9272-61f0a5ae7619.png)

for me this is the only missing information from "Mainsail printing-widget" and I think I can stop using mailsail as fluidd shows the current layer-number and total count :-*

custom buttons in header would be nice also ;-)

**Comment by cadriel** [comment]
Mainsail assumes your prints don't have variable layer heights. :)

If you print a variable layer height print, then those values won't be true. In any case, this will be coming in a future update of Fluidd.

**Comment by maruhe** [comment]
so layer-indicators in gcode-file get ignored by klipper/moonraker?
this would have to be needet to be implemented in klipper first?
the currenlty shown layer-nr in fluidd also fit's only without variable layer height?

**Comment by cadriel** [comment]
Klipper doesn't parse a gcode file up front. In order to get a true layer count, it'd need to read in the entire file file - this is not how Klipper works. 

But otherwise yeah, what you've said is true.. its our best guess without taking into account variable layer heights.
