### ISSUE TITLE
Thumbnails not working if cura slicer

### ISSUE THREAD

**Issue by markwinger** [cadriel/fluidd#132]
I wanted to get thumb nails to work, but I am using Cura.  I found a post processing plugin to add a thumbnail.  But it did not work when I loaded it.  If I added:
; generated by PrusaSlicer 2.3.0+win64 on ....
to the gcode, the thumbnail will display.  I have worked around it by modifying the plugin to insert the line but it needs to change to accept:
;Generated with Cura_SteamEngine 4.8.0

**Comment by cadriel** [comment]
This is a moonraker issue. I think further support for this has just been merged to help support Cura thumbs tho, but you might want to look into the moonraker repo for further help here.
