### ISSUE TITLE
Requested Speed display isn't impacted by speed adjustments

### ISSUE THREAD

**Issue by johanmalay** [cadriel/fluidd#133]
If the print speed is adjusted mid print, the displayed "requested speed" in the UI does not update against the multiplier put in place by the speed adjustment.

Ideally, the requested speed should reflect what the printer is trying to print.

**Comment by cadriel** [comment]
Yeah, i have plans to apply the multiplier to this value. Should be in the next release.

**Comment by cadriel** [comment]
This will be in the next release.

**Comment by johanmalay** [comment]
Awesome, thanks!
