### ISSUE TITLE
Button JOBS is gray.

### ISSUE THREAD

**Issue by anjoku** [cadriel/fluidd#136]
hello, i installed fluidd with the help of KIAUH.
fluidd: v1.6.1-9926453

I am using an Orange Pi Lite. Controlling the printer works. But I can't load files. My Jobs button is gray and I can't choose it.

What am I doing wrong?

Many thanks
Andre
![2021-02-06 10_32_29-kossel _ Printer Configuration](https://user-images.githubusercontent.com/72342904/107114520-b35b7380-6866-11eb-9887-5133bd2a34e7.png)
[klippy.log](https://github.com/cadriel/fluidd/files/5936566/klippy.log)
[moonraker.log](https://github.com/cadriel/fluidd/files/5936567/moonraker.log)

**Comment by anjoku** [comment]
I installed it again yesterday. Armbian.
The following order:
User Andre

1. Armbian and upgrade
2. KIAUH
From KIAUH
1. Klipper
2. Moonraker
3. Fluid

The printer can be controlled, but Jobs is still not accessible

**Comment by cadriel** [comment]
jobs is only available once moonraker / klipper tell fluidd it is. Are you getting other warnings or errors in fluidd? The issue you're describing suggests your virtual_sdcard is not configured properly or your printer isn't connected.

**Comment by cadriel** [comment]
Also, you can ask in the various fluidd / klipper channels in discord for further help on this.
