### ISSUE TITLE
[PR] terminal forced to scroll even when Hide temp waits enabled

### ISSUE THREAD

**Issue by ChipCE** [cadriel/fluidd#137]
## Expected Behavior
Can scroll up on the terminal tab when waiting for heating up.

## Current Behavior
When waiting for temp, even with <code>Hide temp waits</code> enabled, the terminal forced to auto to scroll down then wait temp msg received.

## Steps to Reproduce

1. Enable <code>Hide temp waits</code>  
2. Execute M109 or M190  
3. Scroll up

**Comment by cadriel** [comment]
This should be fixed in the next release.
