### ISSUE TITLE
Text under temperature graph is not static

### ISSUE THREAD

**Issue by vladbabii** [cadriel/fluidd#14]
The 0 point moves to the left for a while then snaps back to right side of graph... sometimes it even dissapears.

The timeline on the bottom should be static, only the graph lines should move in time.

![a](https://user-images.githubusercontent.com/4667916/97091706-7b794900-1646-11eb-820c-c53a6ea8c152.JPG)

![b](https://user-images.githubusercontent.com/4667916/97091708-7d430c80-1646-11eb-9956-ccba3ca1604e.JPG)

![c](https://user-images.githubusercontent.com/4667916/97091709-7f0cd000-1646-11eb-8a19-9ade2eb095f1.JPG)

**Comment by cadriel** [comment]
This is how the graphing lib works..
