### ISSUE TITLE
Fluidd causing high CPU usage and memory consumption

### ISSUE THREAD

**Issue by Rickerdo** [cadriel/fluidd#142]
OS: Linux Mint 20.1 64-bit
Browser: Vivaldi 3.6.2165.36 (Stable channel) (64-bit)
Fluidd: v1.6.3-59f26d1

While sitting completely idle, connected to a Pi running klipper, the Fluidd dashboard causes excessively high CPU usage and high memory consumption. Nothing is being printed, nor are any tasks being performed within the Fluidd browser tab. Screenshot of Vivaldi task manager attached.

![2021-02-09_09-03](https://user-images.githubusercontent.com/6199259/107382653-be581300-6ab5-11eb-8c9f-8113953cfed6.png)

**Comment by cadriel** [comment]
It's likely the chart, which is a known issue.

The next release implements a new chart - which is much more performant. Please re-open this if the issue still exists after this.
