### ISSUE TITLE
Page reload on setting of heated bed

### ISSUE THREAD

**Issue by nicedevil007** [cadriel/fluidd#143]
Heya,

after a fresh connection to the printer on the first entering of a number for the heated bed temperature the whole Fluidd webui homepage is refreshing without adding the temperature to the bed.

I always do this to preheat quick to a certain temp. So I'm entering via numpad the temperature and hit ENTER, after Enter homepage refreshes.

On the 2nd attemp it will work, 100% reproduceable.

![image](https://user-images.githubusercontent.com/17103076/107702151-1d867500-6cba-11eb-9d52-48cd2eb22f03.png)

**Comment by cadriel** [comment]
This should be resolved in the next release, please re-open if its not. Thanks!
