### ISSUE TITLE
Cannot Access fluid from multiple computers 

### ISSUE THREAD

**Issue by Custom3DProducts** [cadriel/fluidd#145]
When trying to access fluid from other computers on the network it only brings up the add printer screen. Putting in http://fluidpi.local also doesnt work. Works fine from my other computer. 
![Capture](https://user-images.githubusercontent.com/34868577/107839107-a7484800-6d77-11eb-8dba-968b0b110754.PNG)

**Comment by cadriel** [comment]
Please see the documentation here;
https://github.com/cadriel/fluidd/blob/develop/docs/setup/moonraker.md

Or join the Discord for help. In your case, you need to setup `cors_domains` or access fluidd by its host.

**Comment by Custom3DProducts** [comment]
Thank you! 
I added 
`trusted_clients:
 10.8.121.0/24`
and 
`cors_domains:
  http://10.8.121.103:80`
works perfectly now!
