### ISSUE TITLE
Performance: All console history entries are re-rendered

### ISSUE THREAD

**Issue by Piezoid** [cadriel/fluidd#147]
When the console history is full (1000 entries) new entries are displayed very slowly and the frame time reach ~1s on Chrome and Firefox. This is most obvious with big outputs (`DUMP_TMC` or tuning tower with a spiralized contour)
[Profile screeshot](https://user-images.githubusercontent.com/3748582/107860965-fc04c500-6e42-11eb-96cd-082811c53da1.png)

Reducing `config.CONSOLE_HISTORY_RETENTION` to 100 solved the problem, confirming the O(n) render time theory.
The DOM view shows that all entries and their container gets updated (pink flash) each time a new one is added.

I've tried to key the `ConsoleEntryWidget`s `v-for` with a monotonic key, instead of the dequeue's indices, to help the diffing algorithm avoid shifting the content of all entries. This allows to use `v-once` inside console entry, which was not working before because of the content shift. It helped a bit (frame time dropped to 400ms), but still very slow.

<details>
     <summary>Draft patch</summary>

```diff
diff --git a/src/components/widgets/ConsoleEntryWidget.vue b/src/components/widgets/ConsoleEntryWidget.vue
index d49f9eb..075c6ab 100644
--- a/src/components/widgets/ConsoleEntryWidget.vue
+++ b/src/components/widgets/ConsoleEntryWidget.vue
@@ -1,5 +1,5 @@
 <template>
-  <v-layout class="console-item">
+  <v-layout v-once class="console-item">
     <span
       v-if="value.time"
       class="grey--text text--darken-2 mr-3 d-none d-sm-block">
diff --git a/src/components/widgets/ConsoleWidget.vue b/src/components/widgets/ConsoleWidget.vue
index 7987f3a..b591388 100644
--- a/src/components/widgets/ConsoleWidget.vue
+++ b/src/components/widgets/ConsoleWidget.vue
@@ -10,8 +10,8 @@
       ref="console-wrapper"
     >
       <console-entry-widget
-        v-for="(item, index) in availableItems"
-        :key="index"
+        v-for="item in availableItems"
+        :key="item.key"
         class="console-item"
         :value="item"
         @click="handleEntryClick"
diff --git a/src/store/socket/index.ts b/src/store/socket/index.ts
index 771bbfb..fa3cfce 100644
--- a/src/store/socket/index.ts
+++ b/src/store/socket/index.ts
@@ -14,6 +14,7 @@ export const defaultState = (): SocketState => {
     error: null,
     endstops: {},
     console: [],
+    consoleCounter: 0,
     availableCommands: {},
     chart: [],
     macros: [],
diff --git a/src/store/socket/mutations.ts b/src/store/socket/mutations.ts
index aa20713..7b37945 100644
--- a/src/store/socket/mutations.ts
+++ b/src/store/socket/mutations.ts
@@ -96,6 +96,8 @@ export const mutations: MutationTree<SocketState> = {
       state.console.shift()
     }
     // state.console.unshift(entry)
+    entry.key = state.consoleCounter
+    state.consoleCounter++
     state.console.push(entry)
   },
   setMacros (state, macros: Macro[]) {
diff --git a/src/store/socket/types.ts b/src/store/socket/types.ts
index 78ee806..7ded932 100644
--- a/src/store/socket/types.ts
+++ b/src/store/socket/types.ts
@@ -1,5 +1,5 @@
 export interface SocketState {
-  [key: string]: boolean | SocketError | EndStops | ConsoleEntry[] | ChartData[] | string | string[] | Printer | null;
+  [key: string]: boolean | SocketError | EndStops | ConsoleEntry[] | ChartData[] | string | string[] | Printer | null | number;
   open: boolean;
   connecting: boolean; // if the socket is down, are we still attempting to reconnect?
   ready: boolean;
@@ -10,6 +10,7 @@ export interface SocketState {
   plugins: string[]; // active plugins (device_power)
   failed_plugins: string[];
   console: ConsoleEntry[]; // console stream
+  consoleCounter: number;
   availableCommands: GcodeCommands; // available gcode commands
   chart: ChartData[]; // chart data
   printer: Printer;
@@ -163,4 +164,5 @@ export interface ConsoleEntry {
   message: string;
   type: 'command' | 'response';
   time?: number;
+  key: number;
 }
```

</details>

[Profile screeshot](https://user-images.githubusercontent.com/3748582/107860812-f5298280-6e41-11eb-8d3a-0de12643112b.png)

Possibly, implementing a virtual scrolling would help the most, but not being able to avoid rendering of all entries is cumbersome.

**Comment by cadriel** [comment]
Yep. This is likely due to implementation and the changes recently to do with filtering, and command clicks.

Really the data should be appended once without the need for additional rendering on already appended items.

I'll take a look at making some adjustments here for an upcoming release.

**Comment by cadriel** [comment]
Ok, so there was some nasty things going on here;

1. Items were re-rendering as the array changed. This should no longer be happening, due to items now having an actual unique key over and above their index.
2. Some slowdown was also introduced by slicing the array on the watcher. I was doing this because I had to determine if there was a change to the array in order to determine if I needed to scroll to the bottom or not. This is still happening now, but i'm doing a shallow clone in the getter instead. The array still causes a re-render of items if you change the filter applied to the data (i.e., toggle the temp waits option), which leads me to the last point;
3. We need a virtual scroll. This will prevent the wait times associated with having to re-render 1000+ dom elements (or having to remove them.

The issue isn't having 1000 items in the DOM, but having to remove / add them IS. I have steps 1 and 2 sorted, and am working on a solution for 3.

**Comment by cadriel** [comment]
@Piezoid 

I have a fix in place. Would you be able to run your tests on the attached test build? If you come up with no issues - I'll merge. Thanks!
[fluidd.zip](https://github.com/cadriel/fluidd/files/5978524/fluidd.zip)

**Comment by Piezoid** [comment]
> I have a fix in place. Would you be able to run your tests on the attached test build? If you come up with no issues - I'll merge. 

Great, thanks! I can confirm that it's much more fluid now, with the virtual scrolling.

> The issue isn't having 1000 items in the DOM, but having to remove / add them IS.

Yes, the issue was updating/rendering all of them for inserting a single entry.

I think 1. and 3. were the most important improvements, ad they reduce the size of DOM updates which was the point of friction. I was a bit concerned about the added complexity and dependencies of virtual scrolling, but since you went for it, I guess it's fine.

One potential improvement would be to batch multiple insertions in one update. Currently, it seems that only a single entry can be added per DOM update.
