### ISSUE TITLE
Feature request: Setting to invert Z control

### ISSUE THREAD

**Issue by cjackson234** [cadriel/fluidd#15]
**Issue:** My railcore (and quite a few other designs) have beds that drop rather than a gantry or X axis that is raised. So for me, up and down are backwards on the toolhead control.

**Suggestion:** I would like to see a setting that allows me to invert this control and save it to the settings json.

**Comment by cadriel** [comment]
Yep, sounds super valid. Will get it done!

**Comment by cadriel** [comment]
Can you clarify exactly how you'd like to see this?

I.e., do you want the icons to stay the same - but the gcode sent to be reversed?

Also - do you want the same application for X axes?

**Comment by cjackson234** [comment]
Yes to both. I want the icons to stay the same on the UI and the command behind them to be inverted.

**Comment by cadriel** [comment]
This is implemented for the next release. You'll be able to invert each of the configured axis.
