### ISSUE TITLE
Featue request: Extruder and BED PID Tuning in UI

### ISSUE THREAD

**Issue by Xenomorphdelombre** [cadriel/fluidd#150]
Hi, first f all thank you for this great UI to use with Klipper. I love it. I would like to know if it would be possible to add PID Tuning in the PRINTER config with desired temperature? For the BED and EXTRUDER. 

Thanks!

**Comment by kubroid** [comment]
Put this in your config file:
```
[gcode_macro PID_TUNE_EXTRUDER]
gcode: PID_CALIBRATE HEATER=extruder TARGET=210 WRITE_FILE=1

[gcode_macro PID_TUNE_BED]
gcode: PID_CALIBRATE HEATER=heater_bed TARGET=60 WRITE_FILE=1
```
and then call that macro(s) from UI.

**Comment by Xenomorphdelombre** [comment]
Thanks! that should do it
