### ISSUE TITLE
Color for Powerplug on "deactivated" State is different than on other menus

### ISSUE THREAD

**Issue by nicedevil007** [cadriel/fluidd#154]
Just small cosmetic thing.

The color for the font is different during a print of the power plugin in comparison to services f.e.

It is much darker:
![image](https://user-images.githubusercontent.com/17103076/108266539-85313a00-716a-11eb-825f-e27b25f2350f.png)

Here the services in "light grey":
![image](https://user-images.githubusercontent.com/17103076/107879001-96621880-6ed6-11eb-884c-3d55dce32c83.png)

**Comment by cadriel** [comment]
Thanks for posting this. Should be fixed in the next release cycle. Please feel free to re-open this ticket if it doesn't look right.

Cheers!
