### ISSUE TITLE
Camera URL "cacheBust" is not valid parameter

### ISSUE THREAD

**Issue by kenblu24** [cadriel/fluidd#155]
I just updated to v1.7.1 from something like v1.6.9? I forget what version I had before. Camera embedding is not working for me anymore, whereas it previously did. 

It seems fluidd is adding an anti-cache parameter to the URL to ensure that a stale image is not loaded. However, my webcam supports a live stream via the file `/video.cgi`. Something about the added URL parameter is causing it to not load for me. 

![2021-02-17_16-03-13](https://user-images.githubusercontent.com/7890808/108267929-d70d9c00-7139-11eb-897b-3efe647f67b9.png)

Here's what does not load for me:

`http://sub.test.net:48000/video.cgi=&cacheBust=1613595163086`

The above URL will give me a File Not Found error.

Here's what does load for me: 

`http://sub.test.net:48000/video.cgi`**`?`**`=&cacheBust=1613595163086`

`http://sub.test.net:48000/video.cgi?cacheBust=1613595163086`

I'm assuming this is standard behavior for web server stuff, but in case it isn't, my webcam is a D-Link DCS-930L

**Comment by cadriel** [comment]
Yep, that's an incorrectly formatted URL.

I'll get a fix in for the next release, sorry about that.

**Comment by cadriel** [comment]
This is sorted in code, please re-open if this is not resolved with the next release. Thanks for reporting!
