### ISSUE TITLE
INVALID Error

### ISSUE THREAD

**Issue by ChrisYOLO** [cadriel/fluidd#157]
I've been getting this error and i don't know whats the cause of it. I didn't change or do anything. All i did was print a file, turn off my printer, open it the next day and boom i have this error and i can't print (with the right speed)
[moonraker (1).log](https://github.com/cadriel/fluidd/files/6023520/moonraker.1.log)
[klippy (2).log](https://github.com/cadriel/fluidd/files/6023521/klippy.2.log)
![Screenshot_4](https://user-images.githubusercontent.com/58643436/108739253-22aab600-753d-11eb-89bc-ef5598cca674.png)

**Comment by cadriel** [comment]
Did you run an update?

If you roll over the invalid errors, you'll see a tooltip explaining the issue. If this printer was in a working state prior, then the only way I can think of it hitting this state is if an update failed for all three components.

Your best bet at this point is to manually update the components. I'd also check your system logs to see if something else is going on there.

Often failed updates can be pinpointed toward network issues too, so if you're on wifi - check for packet loss / issues.

Manual update docs can be found here;
https://github.com/cadriel/fluidd/blob/develop/docs/updates/manual-updates.md
