### ISSUE TITLE
I get an INVALID error

### ISSUE THREAD

**Issue by ChrisYOLO** [cadriel/fluidd#158]
For some reason i get this error displayed below. I haven't changed anything in my setup and this has happend to me twice. Printer is connected.
![Screenshot_4](https://user-images.githubusercontent.com/58643436/108756090-be91ed00-7550-11eb-883d-9bf6c78d3d4f.png)
[moonraker (1).log](https://github.com/cadriel/fluidd/files/6024491/moonraker.1.log)
[klippy (2).log](https://github.com/cadriel/fluidd/files/6024492/klippy.2.log)

**Comment by ChrisYOLO** [comment]
I saw that you closed the previous one but i didn't get to reply. No the printer waws not updating and i have tried manually updating everyhitng, still not working :/

**Comment by cadriel** [comment]
Please, stop creating issues.

You can still reply to a closed issue.

This is not directly a Fluidd issue. The state of those updates comes from Moonraker. It's telling you that the repositories are invalid. Please ensure they're not forks - and that you haven't touched any of the files inside those folders.

Also - feel free to reach out in Discord, where this would be more easily diagnosed.
