### ISSUE TITLE
Jobs/Config on Dashboard - Buttons not aligned

### ISSUE THREAD

**Issue by jrdnlc** [cadriel/fluidd#159]
<img width="693" alt="Screen Shot 2021-02-18 at 12 40 07 PM" src="https://user-images.githubusercontent.com/15741144/109043270-023a4300-7686-11eb-820f-4b071f8e31cb.png">
<img width="266" alt="Screen Shot 2021-02-13 at 5 39 02 PM" src="https://user-images.githubusercontent.com/15741144/109043373-1f6f1180-7686-11eb-923a-2b8a35e1a0e0.png">

**Comment by cadriel** [comment]
I can't replicate this. Can you provide further information on your browser, and operating system? Also - what screen resolution / size is your browser set at?

**Comment by jrdnlc** [comment]
OSX and Safari. It happens on latest version of iOS as well![image](https://user-images.githubusercontent.com/15741144/110210225-84c0c080-7e45-11eb-8d7d-10fe432e1e79.jpeg).

**Comment by cadriel** [comment]
Hrm, I'm on OSX, and have tested in Safari - and don't have this issue.

Do you have your browsers set with a zoom? Can you try hitting CMD-0, or go into the menu and ensure zoom is set to 0 / off?

**Comment by jrdnlc** [comment]
Zoom is at 0. I can replicate on iOS so I highly doubt that’s it

**Comment by cadriel** [comment]
Ah I can see it on IOS. That's enough for me to better diagnose, cheers.

**Comment by cadriel** [comment]
This will be fixed in the next release.
