### ISSUE TITLE
FR: Mqtt

### ISSUE THREAD

**Issue by dinomaskot** [cadriel/fluidd#160]
First of all..Love the project!

Second, I have a future request..it would be great if there was an mqtt integration, so that smart switches could be used to turn printers on/off.

Thanks

**Comment by cadriel** [comment]
I believe this would be a moonraker request, not one of Fluidd the UI - since moonraker is our API.

Also, there's already support for some iot devices in place - so check that out. Fluidd supports all of the plugins moonraker exposes, so you might already have a solution.
