### ISSUE TITLE
Would you like to add FluiddPI to List of Distributions using CustomPiOS section?

### ISSUE THREAD

**Issue by guysoft** [cadriel/fluidd#161]
Hey all, 
Was wondering if you would like to add FluiddPI to the CustomPiOS list of distros using it:
https://github.com/guysoft/CustomPiOS#list-of-distributions-using-custompios

A PR is welcome :)

**Comment by cadriel** [comment]
Hey, thanks for the headsup.

https://github.com/guysoft/CustomPiOS/pull/117

PR in place.

**Comment by guysoft** [comment]
Thanks! Closing.
Also fixed a typo and a syntax error :)

**Comment by cadriel** [comment]
hah. thank you. :)
