### ISSUE TITLE
Thumnail shows from previous print

### ISSUE THREAD

**Issue by markwinger** [cadriel/fluidd#166]
When I print gcode that contains a thumbnail, the images shows up in the print panel of the dashboard.
But If I then print a gcode file that does not contain a thumbnail, the thumbnail of the previous print remains on the panel.

**Comment by cadriel** [comment]
Ok, I *think* I have this figured out.

Please re-test and let me know if its still an issue with the next release.

Thanks for reporting!

**Comment by markwinger** [comment]
I updated to the latest but the version and not change.  Update says v1.9.0.  I don’t think I have the fix.  How do I get it?

**Comment by cadriel** [comment]
1.9 was released a while ago, this change has not been released yet.

**Comment by cadriel** [comment]
1.10 is now out. Please check with this release! :)

**Comment by markwinger** [comment]
I tested it on v1.10.  The problem appears to have been corrected.

**Comment by cadriel** [comment]
Fantastic, thanks
