### ISSUE TITLE
Add option to rollback version update in software updates.

### ISSUE THREAD

**Issue by Nandox7** [cadriel/fluidd#169]
This come up just now with the last updates.
A broken commit in Moonraker is making it impossible to submit gcode directly from PrusaSlicer (guess the slicer is not relevant)

But the idea is that due to an update it left the system in a broken state, so it would be good to have an option to rollback ot previous update to cover for this issues.

**Comment by cadriel** [comment]
The slicer upload is not an issue, see the latest docs here:
https://docs.fluidd.xyz/configuration/moonraker#octoprint_compat-block

Rollbacks are not likely to come soon, as they're dependent on other components having support for dependencies. I'm keeping track of these things, and if this becomes a possibility I'll add it.

Thanks for the feedback tho, it's appreciated.

Cheers!
