### ISSUE TITLE
Tachometer bug

### ISSUE THREAD

**Issue by Afterschnitzel** [cadriel/fluidd#170]
Hello, I just updated Fluid to 1.10.0
I like rpm meter feature. But there are bugs.
Nozzle fan rpm are showing at part fan and part fan rpm are showing at nozzle fan.
And I really can live without 12+ decimal numbers. Is possible to remove decimals and make digits bigger?
![image](https://user-images.githubusercontent.com/60582475/110181348-dea49480-7e0b-11eb-8f29-3877d53b7426.png)

**Comment by cadriel** [comment]
The extra digits i'll take care of.

However, the report re: rpm showing for different fans - if true, would be a klipper issue I think.. since I only report what is given to me for those values. Will double check my side tho.

**Comment by cadriel** [comment]
A fix for this is in develop, it'll be in the next release.

I couldn't see any reason why rpm's would be swapped between fans..

**Comment by Afterschnitzel** [comment]
Oh, sorry, cadriel.
It was my fault, I checked klipper config and I had to repair my fan pins. Now it is OK.
Thanks for your response.

![image](https://user-images.githubusercontent.com/60582475/110202453-0d9d2380-7e69-11eb-8db7-31d61d15e01d.png)
