### ISSUE TITLE
[FR] Exclude Region Functionality

### ISSUE THREAD

**Issue by NovaViper** [cadriel/fluidd#171]
Hi! Recently I went over to Fluidd from Octoprint and it's been working fine. The one thing I’m really missing the most is the [“Cancel Object”](https://plugins.octoprint.org/plugins/cancelobject/) functionality.

There were a couple of people who asked on the developers of Klipper and Moonrakers and were told that it was neither an issue on Klipper's or Moonraker's side.

**Comment by cadriel** [comment]
Cancel Object based functionality will be a collaboration across klipper, moonraker and clients.

**Comment by cadriel** [comment]
I'm going to close this for now, it's on the roadmap - but requires further work down stream to happen first.
