### ISSUE TITLE
asked feature upload from slicer

### ISSUE THREAD

**Issue by tjengbudi** [cadriel/fluidd#172]
hello, looks like super slicer can upload gcode after slicing and it is really nice feature. 
if this implemented with klipper,  where it will be implemented? moonraker or fluidd? 
in my mind i guess it must be in the fluidd side. am i right?
can it be implemented?

**Comment by jwkicklighter** [comment]
Hey @tjengbudi, this is already implemented. Simply put the Fluidd IP/Port in Super Slicer for the Octoprint URL and it should work for you.

**Comment by cadriel** [comment]
As noted, this is already in place.

https://docs.fluidd.xyz/features/slicer-uploads
