### ISSUE TITLE
Feature Request: Customize Z Offset values in Tool Dashboard Widget

### ISSUE THREAD

**Issue by KurioHonoo** [cadriel/fluidd#175]
Thank you Cadriel for suggesting that I create a Feature Request.

The ability to customize the Z Offset values under the Tool widget via the UI Settings Customizer.
The current values of 0.01 and 0.05 are great, but being able to choose even smaller or potentially greater values would be a nice addition. For example, when I was running Marlin I had my babystep values in 0.005 increments.

**Comment by cadriel** [comment]
This will be in the next release.
