### ISSUE TITLE
Latest FluiddPI image doesn't boot

### ISSUE THREAD

**Issue by hakimio** [cadriel/fluidd#179]
FluiddPI `v1.9.0-1` doesn't boot for me. Was it tested?

**Comment by cadriel** [comment]
What makes you think it's not booting? The image is built using automation tools and its pretty unlikely it'd fail this side.

**Comment by hakimio** [comment]
I have a screen connected to Raspberry Pi. MainsailOS  works fine on the same PI/SD card.

**Comment by cadriel** [comment]
have you tried redownloading the image?

**Comment by hakimio** [comment]
No, have you tried testing it on your PI?

**Comment by cadriel** [comment]
no - i'll give it a shot locally.

**Comment by cadriel** [comment]
What's the error you're getting on screen?

**Comment by hakimio** [comment]
The screen just keeps flashing and rebooting for me. Does it work on an emulator?

**Comment by cadriel** [comment]
I think there were upstream changes that have caused a problem. I'm running test builds now, will update the release with a -2 when i've confirmed its good again.

**Comment by hakimio** [comment]
Which upstream dependency broke it? Do you have a bug report reference?

**Comment by cadriel** [comment]
OctoPi is having the same failures. It's something to do with the mjpgstreamer build.

**Comment by cadriel** [comment]
This is now resolved. I've run a test build and double checked it, and its looking good again.

A new img will be generated with the next release.
