### ISSUE TITLE
Can't update Klipper

### ISSUE THREAD

**Issue by AGFazio** [cadriel/fluidd#187]
After installing Fluidd and Klipper. I can get everything setup but when I attempt to go through the updates required it states the the Klipper install is DIRTY. How would I update Klipper?

**Comment by cadriel** [comment]
This is most likely to do with a failed update.

A DIRTY status means the klipper git repo has been touched in some way.

If this was caused by a failed update, then you can try;

```bash
# SSH into your PI
cd ~
sudo service klipper stop
mv klipper klipper_old
git clone https://github.com/KevinOConnor/klipper.git
sudo service klipper start
```
