### ISSUE TITLE
Too many gcode files overflow the Jobs tab

### ISSUE THREAD

**Issue by yanfali** [cadriel/fluidd#19]
If there are too many jobs uploaded, when you navigate to the tab the first time after a reload, only the oldest jobs are shown and there's no obvious way to scroll; there are no scrollbars. Deleting some jobs brings the most recently submitted job back into view.

**Comment by cadriel** [comment]
Are you able to;

- Give me an estimate of how many gcodes / folders you have to cause this and;
- Post a screenshot of what it looks like?

**Comment by yanfali** [comment]
I can't reproduce it. The scrollbar appears now. Let me try on mobile. It's working. I guess this might have been a cached version. Closing.
