### ISSUE TITLE
Uploading no longer works

### ISSUE THREAD

**Issue by tomohulk** [cadriel/fluidd#194]
After the latest update, v1.11.0 the file upload function no longer works.  I tried rebooting the host and still nothing.  No errors or anything that I can tell.  Can upload the moonraker log if that will help.

thanks.

**Comment by Booner99** [comment]
I have just done the update too and i can not upload files any more?

Thank you.

**Comment by tomohulk** [comment]
@Booner99 as a workaround you can SCP your files to virtual SD file location
`scp ./Path/To/file.gcode pi@fluiddpi.local:/Path/To/VirtualSDCard`

**Comment by cadriel** [comment]
This is fixed in 11.11.

Also, drag and drop uploads still work in fluidd. The bug was only when using the button to upload.
