### ISSUE TITLE
Different color schemes and names for different printers

### ISSUE THREAD

**Issue by constantinef** [cadriel/fluidd#197]
Hello!
First of all, Thank you very much for your work on this awesome app!

Before [v1.11.1](https://github.com/cadriel/fluidd/releases/tag/v1.11.1) or [v1.11.0](https://github.com/cadriel/fluidd/releases/tag/v1.11.0), it was possible to configure different hosts (for example 192.168.1.71:7125 and 192.168.1.71:7126) in the same interface - with different names and a different color scheme for printers, which was very convenient, as it helped to immediately understand which printer you were working with now.
After upgrade - color scheme and printer name are applied regardless of the selected host.
![image](https://user-images.githubusercontent.com/1788265/112715059-1b394c80-8eef-11eb-85b8-1fed5a47fc7e.png)
Is this a bug?

**Comment by cadriel** [comment]
Yes, Fluidd supports this.

In your case, this is likely a mis-configuration in moonraker.

Moonraker has a database, and by default - stores this database in the `~/.moonraker_db` folder on your PI.

If you have multiple moonraker instances on a single PI, then they will all share the same database - unless you explicitly define it.

So, with your example above - Fluidd is saving the printer name and color theme fine, but your other printer is also saving this data into the same place.

Please see here for information on how to configure moonrakers database path;
https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#server

Thanks!
