### ISSUE TITLE
missing Docs directory at Configuration Files frame

### ISSUE THREAD

**Issue by ZabejAga** [cadriel/fluidd#209]
Frame **Configure -- Configuration files**  missing **Docs** folder. it is hard to adjust printer without it as it holds 'prints' subfolder with STL for tests.

**Comment by cadriel** [comment]
I can add the docs folder back, but note that it's not something you can print directly from.

**Comment by ZabejAga** [comment]
"docs" share gives possibility to directly download STL file for slicer. Without  ssh/sftp etc connections. It's really handy.
