### ISSUE TITLE
All temps in graph

### ISSUE THREAD

**Issue by LeandroMarceddu** [cadriel/fluidd#21]
As title says. Is there a way to display all the temperatures it senses in the graph below it? As seen in screenshot I have a bedcorner sensor, which isn't displaying in the graphs.
![image](https://user-images.githubusercontent.com/227830/97755301-313a1100-1af9-11eb-8886-f0e7a66234b9.png)

**Comment by cadriel** [comment]
Possibly.. can you paste the section of your config where you define this sensor?

**Comment by cadriel** [comment]
Also, does the current temp in your screenshot have a min / max value tooltip?

**Comment by LeandroMarceddu** [comment]
> Also, does the current temp in your screenshot have a min / max value tooltip?

It does. Which rather confused me at first before I knew what it was about. 


> Possibly.. can you paste the section of your config where you define this sensor?

[temperature_sensor bedcorner]
sensor_type: NTC 100K beta 3950
sensor_pin: P0.24

**Comment by cadriel** [comment]
This is fixed, will be available next release. :)
