### ISSUE TITLE
After add second printer, fluidd forward webui to first printer

### ISSUE THREAD

**Issue by tayanov** [cadriel/fluidd#210]
Mainsail work with two printers is ok.
i try add seconв moonraker at 7126 port.  i see fluidd with first printer at 7125 port.
Name of both printers as first printer name. But adress is difrent...
What is it?

fluidd work perfectly with two printers perfectly before upgrade.
Power device tasmota glitch too ...

**Comment by constantinef** [comment]
Maybe it is the same issue - https://github.com/cadriel/fluidd/issues/208
Config now stores in moonraker db - [v1.11.0](https://github.com/cadriel/fluidd/releases/tag/v1.11.0)
`- Configuration moved to Moonrakers database.`

**Comment by tayanov** [comment]
thanks. close pls
