### ISSUE TITLE
Lost socket connection on iOS

### ISSUE THREAD

**Issue by LazaroFilm** [cadriel/fluidd#22]
![IMG_6714](https://user-images.githubusercontent.com/18351100/97767303-b15c7880-1af1-11eb-88e0-de441b02adef.PNG)

fluidd works on my computer but it shows this on iPhone. It also seem to try to refresh now and then (the text flashes to something else but too fast to read it)
© 2020 fluidd: v0.0.10-7091f23 , klippy: v0.9.1-13-g79877acb

**Comment by cadriel** [comment]
This suggests your phone can't connect? I'd suspect its because it might not be on your wifi - or lost connection.
