### ISSUE TITLE
Feature request: more Z-offset buttons

### ISSUE THREAD

**Issue by DrDaveone** [cadriel/fluidd#221]
now Z-offset restricted with 2 preset-buttons: 0.01 and 0.05, but to calibrate bed proper, need more prescision as 0.001-5 (marlin-style)

**Comment by cadriel** [comment]
You can configure these in the interface settings page. Or are you saying you want more than two options?

**Comment by cadriel** [comment]
I've updated this so you can configure up to 4 buttons, and added 4 defaults of `0.001, 0.005, 0.01, 0.05`
