### ISSUE TITLE
Make graph hight variable 

### ISSUE THREAD

**Issue by Coffee0297** [cadriel/fluidd#23]
Hello,
Can we make this graph scale with the max current temp +20 or so? Or even a custom setting so users can define themself. So when hottest thing is 50c then the graph goes to 70c and so on
![image](https://user-images.githubusercontent.com/43273303/98160492-910c2f80-1ede-11eb-90a0-0d92648ca35b.png)

**Comment by cadriel** [comment]
this is now implemented. Scale will adjust based on the max temp you have defined in your printer.cfg + 60. (60 is the graphs step size.. )

Will be available in the next release.
