### ISSUE TITLE
[BUG] Tool panel flickers while dragging Jobs into and out of folders.

### ISSUE THREAD

**Issue by StuSerious** [cadriel/fluidd#230]
## Description:
Version: up to dev app, master is also affected.
As per the title, the Tool panel flickers while dragging Jobs into and out of folders.

## Reproducing:
1. Create a Folder;
2. Upload a File;
3. Move any File into or out of a Folder;
4. Tool panel flickers.

### Media:
Here is a GIF:
![flicker](https://user-images.githubusercontent.com/53015230/114088928-da114700-98b5-11eb-9323-542d5104836f.gif)

## Expected behavior:
The tool panel doesn't flicker 

## Solutions considered:
As discussed on discord, this could be done by adding a wait for a file system action.

**Comment by cadriel** [comment]
This is now resolved in develop.
