### ISSUE TITLE
Feature Request: Adding camera resolution settings

### ISSUE THREAD

**Issue by alexcroce** [cadriel/fluidd#234]
It would nice to have option to set via fluidd interface camera resolution for mjpeg streamer.
Thx!

**Comment by cadriel** [comment]
mjpgstreamer is configured specifically via a file in the `/boot` path. This file requires root access, of which we can't safely expose via moonraker / fluidd.

So - other than the options you see now, you won't be able to configure resolution directly in fluidd for the foreseeable future.
