### ISSUE TITLE
Error uploading gcode file

### ISSUE THREAD

**Issue by stpavel** [cadriel/fluidd#235]
When I try upload file , I have get error after process uploading 
**Request failed with the status code 405**
At the same time, I can delete or create directories from the file panel without any problems, that is, everything is ok with permissions

**Comment by cadriel** [comment]
405 is method not allowed, this feels like some other issue.

Do you have any other warnings? Are you connected to klipper? How did you install Fluidd?

**Comment by stpavel** [comment]
No any other warinings . Yes, I connected to klipper. Install trough kiauh script

**Comment by cadriel** [comment]
Are you uploading via button, or drag and drop? Do you get a different result if you drag and drop?

There's an existing bug whereby using the upload button fails, but dragging and dropping works - so i'd like to rule that out.

**Comment by stpavel** [comment]
I tried via button and drag 'n' drop, result the same .

**Comment by cadriel** [comment]
I think you need to inspect your moonraker config. A 405 is being returned from it, so there's likely something else going on.

**Comment by shinuza** [comment]
Could also be coming from nginx or another webserver in-between.

**Comment by cadriel** [comment]
I'm going to close this - seems to be related / unique to user environment.
