### ISSUE TITLE
[Feature Request] Add badge to printed files in file explorer

### ISSUE THREAD

**Issue by tlsomers** [cadriel/fluidd#236]
As it is possible to upload multiple gcode files before actually printing them, it would be nice to add a label or badge to the files that have already been printed. It should be possible to implement this using the history provided by moonraker, which includes the file name.

**Comment by cadriel** [comment]
Files already get marked with their actual print time, and last printed date in the jobs list. This then lets you order by last print date. Is this what you had in mind? Would a label over and above this add value?

**Comment by tlsomers** [comment]
Thanks, I must have just read over that.
