### ISSUE TITLE
[BUG] Unable to upload more than 1 file

### ISSUE THREAD

**Issue by tlsomers** [cadriel/fluidd#239]
I attempted to upload multiple files but after the first file uploaded it froze (see image)

![image](https://user-images.githubusercontent.com/56299065/114282339-859bd200-9a43-11eb-9e84-cb8ae8d84f21.png)

Browser: Firrefox (linux)
Fluidd v1.12.2

**Comment by cadriel** [comment]
How are you uploading? Via drag and drop or the button?

**Comment by cadriel** [comment]
ok, I've reproduced this. Its only an issue when using the button versus drag and drop, so for the moment you can drag instead.

**Comment by cadriel** [comment]
This is resolved for next release.
