### ISSUE TITLE
Feature-Request: Animated progress bar Favicon

### ISSUE THREAD

**Issue by fex42** [cadriel/fluidd#24]
Let me start by saying that Fluidd is a great! Thank you so much for making this cool project!

One small thing that I'm missing compared to Mainsail is the animated Favicon in the browser tab that displays print progress.

Would be great to have such a feature in Fluidd too (not necessarily exactly this animated disk icon that Mainsail has. It could be something like flooding color of the (nice) Fluidd icon).

**Comment by fex42** [comment]
Great that there was such a quick solution available, thank you!
Sadly it didn't make it's way into 1.0 - any chance to have it in 1.0 again?

**Comment by cadriel** [comment]
This should be in the next release.
