### ISSUE TITLE
Move the emergency stop button away from the system menu call button

### ISSUE THREAD

**Issue by constantinef** [cadriel/fluidd#250]
## Is your feature request related to a problem? Please describe.
Several times I accidentally hit the emergency stop button when trying to call up the menu to switch to the second printer.

## Describe the solution you'd like:
Move the button a little further from the system menu call button. 
Perhaps closer to the logo or to the print status section.

## Affected users and/or setups:
Minimize accidental pressing of the emergency stop button and unwanted termination of printing. Especially useful when switching between multiple printers

## Additional Context:
![image](https://user-images.githubusercontent.com/1788265/115053866-44466f00-9ee8-11eb-965e-2453fcf6191f.png)
![image](https://user-images.githubusercontent.com/1788265/115053900-49a3b980-9ee8-11eb-88cd-14a07a55fde4.png)
![image](https://user-images.githubusercontent.com/1788265/115053913-4b6d7d00-9ee8-11eb-840f-7e003453119a.png)
Especially scary when using a phone and tablet - that is, with touch interfaces

**Comment by cadriel** [comment]
I'm going to close this, as I believe the latest release addresses it. Please, feel free to either comment again or join the Discord if you have further thoughts on it.

https://discord.gg/GZ3D5tqfcF
