### ISSUE TITLE
Feature Dashboard Sensors GPIO - (RaspberryPi / OrangePi)

### ISSUE THREAD

**Issue by PatricLeal** [cadriel/fluidd#253]
## IIs your feature request related to a problem?
Currently, it is not possible to validate the operating history during a print or current status of a printer's resources, since we are only able to monitor the standard temperature sensors and temperature sensors of the Raspberry and MCU.

## Describe the solution you'd like:
The solution is very simple, with the use of a dashboard panel it would allow adding more sensors referenced to gpio or hardware, this way the current and historical information would be all on the screen, the solution is similar to the one used in PRTG for control  of iot devices or systems and servers, with the solution it would be possible to find situations in which it could be causing some failure or malfunction of equipment or malfunctioning situation.

## Describe alternatives you've considered:
There are monitoring solutions PRTG, TeamViewer iot, zabbix, nagios, however they are solutions that need other installed applications and hosting of servers or contracting third party services, in addition to losing in the integration factor which would be outside the current platform.

## Affected users and/or setups:
Change affects a group of users who want greater control and security on their printers, especially those using platforms with GPIO availability (RaspberryPi and OrangePi). The benefits are mainly the control of equipment reliability, control of electrical circuits, in addition to the possibility of  control external variables such as humidity, also allowing to turn off equipment or prevent printing in adverse or risky situations (for example, high humility of the environment, over voltage and power problems), such panel availability opens up new opportunities in the management of connected equipment.
----------------------
Prtg Example;
![images - 2021-04-18T231045.379.jpeg](https://user-images.githubusercontent.com/26906375/115172293-574d7080-a09b-11eb-830a-9fd7d60a229e.jpeg)

(Mainsail/Fluidd) Current temperature panel;
![IMG_20210418_231326.jpg](https://user-images.githubusercontent.com/26906375/115172639-11dd7300-a09c-11eb-9d4b-d55e6f66a62b.jpg)

![images - 2021-04-18T231501.308.jpeg](https://user-images.githubusercontent.com/26906375/115172649-17d35400-a09c-11eb-9c5b-f6275616107a.jpeg)

**Comment by cadriel** [comment]
Most of this is outside of the intent of a printer UI, so likely isn't going to happen.

I will say that some data, like CPU throttling and under voltage warnings, along with CPU utilization and low memory warnings ARE coming, and may cover some of what you've mentioned above.

Thanks!

**Comment by PatricLeal** [comment]
> Most of this is outside of the intent of a printer UI, so likely isn't going to happen.
> 
> I will say that some data, like CPU throttling and under voltage warnings, along with CPU utilization and low memory warnings ARE coming, and may cover some of what you've mentioned above.
> 
> Thanks!

Thank you, I will wait for this news, thanks for the return.
