### ISSUE TITLE
Firefox loses connection to moonraker when downloading files

### ISSUE THREAD

**Issue by cubiq** [cadriel/fluidd#254]
## Affected Version(s):
- klipper version: v1.12.2
- moonraker version: v0.5.0-20
- fluidd version: v0.9.1-434

## Platform:
linux, windows

## Hardware Configuration:
host is a RPi3B, MCU is a duet2wifi

## Reproduction Steps/Actual Results
Try to download a file (like a log or a gcode) on firefox. The file is downloaded but the connection to moonraker is lost, moonraker service is still running though. This doesn't happen on Chrome.

PS: this also happens on mainsail

## Log Files:
Log shows no error.
[moonraker.log](https://github.com/cadriel/fluidd/files/6336465/moonraker.log)

**Comment by cadriel** [comment]
This is a firefox issue we recently encountered. I've added a workaround for the next release, and so should be resolved then.
