### ISSUE TITLE
Macros listing order

### ISSUE THREAD

**Issue by alexcroce** [cadriel/fluidd#257]
Is it possible to have ability to choose how to sort Macros in their tab? I.e. I would like to have sorted alphabetically, or using a personalized order.
Thanks!

**Comment by StuSerious** [comment]
hey there @alexcroce! 
thanks for the feature request!

You can defenetely look forward to the next releases!
Cadriel has implemented a lot of cool features for macros and they're coming soon!

(you could take a look at the commit history to get an idea)

Have a nice day!
~Ste

**Comment by alexcroce** [comment]
Great! Thank you so much!
