### ISSUE TITLE
Clarify error/warning: [virtual_sd_card] -> [virtual_sdcard]

### ISSUE THREAD

**Issue by numanair** [cadriel/fluidd#26]
https://github.com/cadriel/fluidd/blob/d2802ddc9d51471dd2973159b743b802d9d20f9c/src/components/cards/KlippyDisconnectedCard.vue#L63

Should just say "[virtual_sdcard]" with one underscore to match Klipper's config.

Additionally, it might be a good idea to add a link to Mainsail's printer.cfg examples. This would make resolving these errors much more intuitive.
https://github.com/meteyou/mainsail/wiki/Printer.cfg

**Comment by cadriel** [comment]
Thanks for spotting. I'd prefer to not link to the mainsail docs, but am aware I need some further docs in Fluidd.

Working on it!

I've otherwise fixed the issue, so closing for now. Thanks!
