### ISSUE TITLE
Feature Request: Delete file after finished printing

### ISSUE THREAD

**Issue by MrNoob0** [cadriel/fluidd#260]
A feature i would like to see is an option to auto delete files after print is finished. I usually delete files after to save space and it would be useful if it was automatic

**Comment by cadriel** [comment]
I think the idea behind this is sound, however - I'm not a fan of making irreversible decisions on behalf of the user, of which I think this falls into.

Perhaps an easier option to remove a file after a print in the status panel, or something similar - may be a viable solution here instead.

So, for the above reasons - I'm going to close this, but will keep in mind other options.

Thanks!
