### ISSUE TITLE
Extrusion on T1 prevented by the temperature of T0

### ISSUE THREAD

**Issue by EduardoOliveira** [cadriel/fluidd#280]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v1.13.0
- moonraker version:
- fluidd version:

## Platform:
(Information about your platform, like the OS or browser you are using.)
Fluiddpi

## Hardware Configuration:
(Information about your hardware configuration. Like MCU, host and setup)
IDEX with a mellow fly 9 drivers

## Reproduction Steps:
1. set T1 to 200deg
2. select T1
3. wait for it to reach 200deg
4. the extrude/retract buttons are unavailable

## Actual Results:
(What happens after the reproduction steps have been followed.)
I'm unable to extrude if T0 it's not hot

## Log Files:
(The log files fluidd provides at Configure > System Control.)
- klipper log:
- moonraker log:

## Additional information
(Extra information relevant to the issue, links to similar issues.)

**Comment by StuSerious** [comment]
more on this here: https://discord.com/channels/762863525818662974/771936287300911185/841066775202234368

**Comment by cadriel** [comment]
I've fixed this in develop. Will require some testing - but should be good for next release. Please re-open this ticket if it's not working for you after the next release!

Thanks!
