### ISSUE TITLE
Link in doc broken

### ISSUE THREAD

**Issue by nesdnuma** [cadriel/fluidd#281]
Hello,

The link to "initial setup" in the configuration page (https://github.com/cadriel/fluidd/blob/develop/docs/configuration/index.md) is broken.

**Comment by StuSerious** [comment]
hey there @nesdnuma!

the docs are meant to be viewed from the official Just the Docs. the links are all working there!
here's the link: https://docs.fluidd.xyz/configuration

have a great day!
~S
