### ISSUE TITLE
Feature Request: Remove all Jobs.

### ISSUE THREAD

**Issue by CraXyOW3** [cadriel/fluidd#286]
## Is your feature request related to a problem? Please describe.
Not a problem, just a creature comfort.

## Describe the solution you'd like:
I would like an option to simply clear all files in the Jobs section.

## Describe alternatives you've considered:
I have been using WinSCP to remove them all or if bored, removing them one by one in fluidd GUI.

## Affected users and/or setups:
Just simply a creature comfort, nothing important at all, but it would be lovely :D

## Additional Context:
Simple version, Remove all, simply as that!
Advanced version, Remove "selected" jobs and then remove. But if one is fiddly with this, they can just aswell remove one by one tbh :P

## Additional AWE!
Just simply amazing job on Fluidd! Amazing!

**Comment by StuSerious** [comment]
hey there @CraXyOW3!

good news, mass file actions are coming in the next release!
you will be able to select jobs with a checkmark or select all to dump them

cheers
~S
