### ISSUE TITLE
Fluidd will say 100% complete when the print is not yet finished.

### ISSUE THREAD

**Issue by hofleverancier** [cadriel/fluidd#293]
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version:  0.9.1-525-g8e74e6aa
- moonraker version: 0.6.0-134-g2db727e
- fluidd version:1.14.0

## Platform:
Chrome browser

## Screenshot(s):
![image](https://user-images.githubusercontent.com/10186837/120079047-7c79c980-c0b2-11eb-80d3-a1160e01887b.png)

Fluidd will say 100% complete when the print is not yet finished.  It's not a big deal, but still a minor blemish imho. 
I suppose if the percentage was not rounded normally, but down, this would be solved.

**Comment by cadriel** [comment]
The printing percentage represents what klipper tells Fluidd, which should also match the LCD display if you have one. Near the end of the print - it's common to see this at 100% prior to the actual completion - which I agree, seems weird.

All of the clients currently handle this a bit differently.

In the future I intend to adjust how this is represented - and hopefully introduce some kind of consistency.

For now tho, this isn't a bug - so closing. Thanks for the input!
