### ISSUE TITLE
Fluidd Did not work after update. 

### ISSUE THREAD

**Issue by Talha909** [cadriel/fluidd#298]
I install the latest lite version of fluidd on the Raspberry PI Zero. Its works great. I saw the update notification. I updated the system. After completion of update it did not work. What's the reason behind this. When i update OS Packages. Its stop working. There is no light on my Rasbeery PI Zero. After that I have to start again. 
![9bc327a5-d618-40a1-9361-9ca98752f969](https://user-images.githubusercontent.com/29024390/120426535-b6d0b880-c389-11eb-8def-05f00e7e65c2.jpg)

**Comment by cadriel** [comment]
Hi! This is not a Fluidd bug, and is more of a support request. Please join us on the Discord for further support!

https://discord.gg/GZ3D5tqfcF
