### ISSUE TITLE
No pages tabs on tablet view

### ISSUE THREAD

**Issue by Aulos** [cadriel/fluidd#30]
Hi,

It's probably a non-issue, but I cannot access tabs on tablet view 

![image](https://user-images.githubusercontent.com/448931/99908591-d18fe980-2ce3-11eb-9eb2-8856dc1dc988.png)

On the mobile view tabs (dashboard, jobs, printer) are in the dots menu, and on the desktop they are on the upper bar. 

I just cannot find them on a tablet view - they are neither on the upper bar nor in the menu.

**Comment by cadriel** [comment]
Ah, that seems like a problem! I'll take a look, thanks!

**Comment by cadriel** [comment]
This will be fixed in the next release, thanks for letting me know!
