### ISSUE TITLE
Hide temp waits - not working on my printer

### ISSUE THREAD

**Issue by windischb** [cadriel/fluidd#300]
Hi!

There is already a resloved issue which tries so solve the same problem... #82 
I'm not sure if this is really a bug or i'm making anything wrong!

Temp wait lines are shown in the console, even if i enable the "hide temp wait" checkbox.
It looks like on my printer there is a 'ok' text at the beginning of the line.
I have no idea where this is comming from...
But it looks like thats why the line on printer is not filtered...

Is there anything you can implement in fluidd to solve this?
Or is this a problem on my side?

Even if this doesn't help much here, but in Mainsail its filtered correctly...

## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.9.1-499
- moonraker version: v0.6.0-47
- fluidd version: v1.14.0

## Screenshot(s):
![image](https://user-images.githubusercontent.com/6182311/120625939-72fdb200-c462-11eb-8996-c59574443a72.png)

**Comment by cadriel** [comment]
Hi! Yes, it's because of the `ok` - but its not an issue your side. I'll have a fix in for this for next release.

Thank you!
