### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by rkr87** [cadriel/fluidd#301]
Would it be possible setup git integration to automatically push to a repo when config files are changed?

**Comment by cadriel** [comment]
I don't think this would be a feature of Fluidd, but perhaps one of Moonraker.

**Comment by cadriel** [comment]
Thanks for the input tho! :)

**Comment by redoz** [comment]
@cadriel I'd like to request this to be reconsidered, I don't think it makes sense to expect Moonraker (a web API) to support this. 
Github integration is an application-level feature imho and should either be in Fluidd itself, or as an add-on/plugin to Fluidd.
