### ISSUE TITLE
German translation incomplete

### ISSUE THREAD

**Issue by phil2sat** [cadriel/fluidd#302]
Fresh git install, latest version v1.14.0-e46475e

after setting language to german some items on dashboard are weird like:
"app.setting.label.show_animations", (Zeige Animationen) 
"app.version.label.os_packages" (System Pakete) 
"app.general.label.uncategorized" (Unkategorisiert) 
"app.setting.title.gcode_preview" (G-Code Vorschau) 

and some more

looks very bugged

maybe better check if transalation  is complete and if not, fallback to english for untranslated content. 

i guess there is no problem if "app.setting.label.extrusion_line_width" stays "extrusion line width" at least till translation for new features is complete 

nice work so far, like it

**Comment by cadriel** [comment]
This is an issue with the current translation files, some of the translations made it through with empty strings. The next release will have this resolved.

Thanks for spotting!
