### ISSUE TITLE
FEATURE REQUEST: Add browser-based slicer support

### ISSUE THREAD

**Issue by VinnyCordeiro** [cadriel/fluidd#309]
That's an idea that appeared on Voron Discord. There's an open source slicer already available called Kiri:Moto, which is hosted here: https://github.com/GridSpace/grid-apps

It is browser-based, but not cloud-based, so the processing is made locally. Also, Kiri:Moto is licensed with the MIT License, which is compatible with GPL, so on that front that shouldn't be a problem.

The support could be added as a module, in order to not bloat the main installation for those who do not want this feature.

**Comment by cadriel** [comment]
Given that Kiri:Moto is already exposed on the web, I don't think integrating it with Fluidd would give any further benefit to what already exists. Secondarily, I feel the aim of Fluidd is to not be a slicer.. that's better left to user discretion.

Thanks for the input!
