### ISSUE TITLE
Editing printer.cfg does not create backups of previous versions

### ISSUE THREAD

**Issue by Andychud** [cadriel/fluidd#311]
When I go to System>Config>printer.cfg and edit/save the file, it does not save a backup of the previous version anymore. This once worked but I recently noticed it has stopped working. I think it may have been after an update.

**Comment by cadriel** [comment]
Klipper is the only thing that would ever create a backup, Fluidd has never done this.

We may provide a way in the future to create a specific backup - but for now, I suggest either turning your config into a git repo or otherwise managing backups yourself. 

Thank you!
