### ISSUE TITLE
[enhancement] Colors or icons for macros

### ISSUE THREAD

**Issue by Ramalama2** [cadriel/fluidd#315]
hi, if you have a ton of macros, it's getting a bit confusing.

It would be awesome, if we can attach or replace macros with icons that we can upload, or at least give a macro a cusom color.

So i could make for example all the most used macros green and leave the more rarely used in any darker color.

It can be anything, just any way to make them more differenciate from each other 🙈

Thanks ✌️

**Comment by cadriel** [comment]
You'll be able to apply color accents to macros in the next release!

Thanks!

**Comment by Ramalama2** [comment]
> You'll be able to apply color accents to macros in the next release!
> 
> Thanks!

Thank you very much cadriel ♥️
