### ISSUE TITLE
Thermals => heater-names invisible when 'Dark mode' is disabled

### ISSUE THREAD

**Issue by maruhe** [cadriel/fluidd#319]
when I disable 'Dark mode' all heater-names have white text on white background in thermals-section
selecting makes the tayt visible - in dark mode all is fine

![grafik](https://user-images.githubusercontent.com/49123648/122066218-d8eb2180-cdf2-11eb-8db8-e2c728a9dfd3.png)

fluidd: v1.14.0-e46475e klipper etc.. on latets master versions, RasPi3B+, all based on mainsailos-image

**Comment by cadriel** [comment]
Fixed in next release!
