### ISSUE TITLE
Allow basic auth in Moonraker url

### ISSUE THREAD

**Issue by RafaelSchridi** [cadriel/fluidd#322]
## Is your feature request related to a problem? Please describe.
I've got my moonraker instance behind a basic HTTP auth, which you access by passing the username and password in the url like shown in the screenshot below.
Currently the form blocks because of the strict regex

## Describe the solution you'd like:
Allowing any characters within the url like this would be great
**https://\*:\*@example.com**

The fix is probably in this regex:
https://github.com/cadriel/fluidd/blob/7e8785d8c30afd80ce85d981a82f9992b525254c/src/components/common/AddInstanceDialog.vue#L94-L99
but I'm too much a dumbass at advanced regex to fix it myself

## Describe alternatives you've considered:
Tried logging in another tab to use the auth in fluidd but that doesn't work.

## Affected users and/or setups:
probably a very small minority who use reverse proxies

## Additional Context:
![image](https://user-images.githubusercontent.com/11460682/122254341-52efd900-cecd-11eb-90e9-63ed8e355bb0.png)
Here it is working in postman:
![image](https://user-images.githubusercontent.com/11460682/122254464-6dc24d80-cecd-11eb-867d-1fa08cee860e.png)

**Comment by cadriel** [comment]
An incoming update adds JWT authentication, natively within Fluidd. I believe this would remove the need for you to have this?

**Comment by RafaelSchridi** [comment]
JWT authentication would indeed remove my need for this, but there are some people who are swear by and only use basic auth. But if it's more than just a regex edit it's not worth the effort.

**Comment by wlhlm** [comment]
I think if implementation mostly centers around fixing this regex, then I would still like to see this implemented. On the surface, basic auth seems less complex and harder to get wrong compared to JWT.

**Comment by RafaelSchridi** [comment]
More options wouldn't hurt right?
Also the webcam URL currently supports basic auth, so why shouldn't the moonraker url also support it?

**Comment by cadriel** [comment]
I've had some more thoughts on this, and done a little research. Passing credentials directly in the URL isn't great practice - especially plain text passwords, and some browsers refuse it, while others have it deprecated.

For those reasons I'd recommend not passing creds in the URL. We could look at defining basic auth as separate inputs to then pass in the request header as an option, but I'd prefer users simply enable auth in moonraker and use the built in mechanisms, or at least give that a try first - as its much more secure.

**Comment by cadriel** [comment]
Any further thoughts on this now that Auth has been released?

**Comment by RafaelSchridi** [comment]
I have switched over to JWT, so for me this is no longer necessary.
