### ISSUE TITLE
Custom gcode buttons with input boxes

### ISSUE THREAD

**Issue by AndrewEllis93** [cadriel/fluidd#325]
I have recently switched from OctoPrint to Fluidd, and there is one particular plugin's functionality that I miss. Custom Control Editor.

Essentially, I was able to use this plugin to have simple input boxes for macros and gcodes.

For example, I had set this up so I can quickly set my PA values:

![image](https://user-images.githubusercontent.com/34943186/122655926-55983b80-d124-11eb-9d4a-7fba6e454519.png)

And this is how the PA button is configured in the settings:

![image](https://user-images.githubusercontent.com/34943186/122655974-cb9ca280-d124-11eb-9f0c-5b58fef5b146.png)

It just takes what you enter in the box, and passes it to that gcode command. 
Sliders would be a nice addition too, but simple boxes would be a great starting point.

**Comment by cadriel** [comment]
Its like you read my mind.

![Screenshot 2021-06-19 183813](https://user-images.githubusercontent.com/205520/122657951-8e88de00-d12d-11eb-8256-184492648c2a.png)

Fluidd will read the params you expose in your macros, and provide UI for you to enter them. The above example I've simply defined a single klipper param, but you can have as many as you wish - and name them anything. You can also define default values - and they would show in Fluidd.

Note - you define these in your klipper macro setup, not within Fluidd.

Closing this as it's an upcoming feature of the next release.
