### ISSUE TITLE
v1.14.0: Unreadable text in Light Mode (Name, Power and Temp) in Thermals

### ISSUE THREAD

**Issue by Baffeaux** [cadriel/fluidd#330]
![20210622FluiddDarkLightMode](https://user-images.githubusercontent.com/86316631/122970148-d4dc7800-d38d-11eb-8871-25808b4f0661.JPG)

## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: v0.9.1-580-g478f26ca 
- moonraker version: v0.6.0-160-gd3df568 
- fluidd version: v1.14.0

## Platform: Windows 10 Home v 20H2, Firefox 89.0.1 (64-bit) and Chrome Version 91.0.4472.114 (Official Build) (64-bit)
(Information about your platform, like the OS or browser you are using.)

## Hardware Configuration: not relevant?
(Information about your hardware configuration. Like MCU, host and setup)

## Reproduction Steps:
1. (Something you did.) Theme: Dark mode
2. (Something you did next.) Theme: Light Mode

## Actual Results: Unreadable text in Light Mode of 'Name', 'Power' and 'Temp' values in Thermals cause text color too light
(What happens after the reproduction steps have been followed.)

## Screenshot(s): attached
(Images or gifs showing the problem, perhaps before/after.) 

## Expected Results: readable text :-) 
(What *should* happen after the reproduction steps have been followed.)

## Log Files: not relevant?
(The log files fluidd provides at Configure > System Control.)
- klipper log:
- moonraker log:

## Additional information
(Extra information relevant to the issue, links to similar issues.)

**Comment by cadriel** [comment]
Hi! Thanks for reporting. This is resolved in the upcoming v1.15 release.
