### ISSUE TITLE
Webcam does not show up in UI

### ISSUE THREAD

**Issue by teunvandenburg** [cadriel/fluidd#341]
After updating fluid to v1.15 the webcam stream does not show up in the fluidd interface.
However when I browse to http://ender.local/webcam/?action=stream I can watch the stream live.

Thank you for the nice interface!!!

## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version:  v0.9.1-587-g72668822
- moonraker version: v0.6.0-170-gc22dcc1
- fluidd version: v1.15.0

## Platform:
Windows 10 google chome
IOS 14 Safari

## Hardware Configuration:
Raspberry Pi 3 Model B Rev 1.2
SKR E3 V2.0

## Actual Results:
(What happens after the reproduction steps have been followed.)

## Screenshot(s):
![Knipsel](https://user-images.githubusercontent.com/31746975/123604120-d5946480-d7fa-11eb-9bda-55f49d8f8114.PNG)

## Expected Results:
(What *should* happen after the reproduction steps have been followed.)

## Log Files:
(The log files fluidd provides at Configure > System Control.)

## Additional information
(Extra information relevant to the issue, links to similar issues.)

**Comment by cadriel** [comment]
Hi, this is a known bug. Please come join us on discord if you'd like a temporary fix for this - it is resolved in develop, ready for the next release.

https://discord.gg/GZ3D5tqfcF
