### ISSUE TITLE
Can't host on a subdirectory

### ISSUE THREAD

**Issue by Salamandar** [cadriel/fluidd#347]
## Affected Version(s):
- fluidd version: v1.15.0

## Platform:
Octopi

## Reproduction Steps:
I tried to set up a reverse proxy with nginx to access fluidd with an url like : `https://print.myhost.com/ender_fluidd`.
It's impossible because resources are loaded from an absolute path (`/js/something.js`) and it's not relocatable to `/ender_fluidd/js/something.js`.

The idea was to get octoprint and fluidd aside, or multiple fluidd instances on the same port (https). It seems it's impossible ?

**Comment by cadriel** [comment]
This is not a bug. Fluidd is a PWA and SPA and requires hosting on the root of a domain.

I'd instead suggest a reverse proxy to subdomain.

**Comment by Salamandar** [comment]
I don't really understand the limitation you're talking about. This is based on Vue, right ? And Vue apps can be hosted on a subpath. I already saw multiple ones.
https://daten-und-bass.io/blog/serving-a-vue-cli-production-build-on-a-sub-path-with-nginx/

**Comment by Sureiya** [comment]
@Salamandar He's got things reversed. You can't have a SPA navigate across subdomains without a refresh. You can have as many as you want on one though, if they're written to support it.
