### ISSUE TITLE
Monaco Editor - Klipper config style inline comments and values not highlighted properly

### ISSUE THREAD

**Issue by MrAntza99** [cadriel/fluidd#350]
Monaco Editor's _inlineComments_ are not highlighted / coloured as should (like when write to own line)
It seems to be klipper config problem.

As you can see, also values aren't highlighted when using : not =  (maybe not issue?)

https://i.imgur.com/kqJIePz.png

**Comment by cadriel** [comment]
This screenshot is not Fluidd?

![Capture](https://user-images.githubusercontent.com/205520/124390378-eccaca80-dcb0-11eb-9b83-998360fedaed.PNG)

**Comment by MrAntza99** [comment]
https://i.imgur.com/xtpnQMK.png
https://i.imgur.com/UeHjqQQ.png

Its Fluidd

**Comment by cadriel** [comment]
The first screenshot you sent has the incorrect theme applied based on the latest release of Fluidd. I notice that your screenshots above are also for an old release of Fluidd.

It might be best if you were to update to v1.15 first - and see if your issue still persists.

The screenshot I posted above, which is directly from fluidd v1.15 - has commenting working correctly.

**Comment by MrAntza99** [comment]
It was just too old version, it seems to work now well.
