### ISSUE TITLE
Webcam.Txt does not make any effect. 

### ISSUE THREAD

**Issue by Talha909** [cadriel/fluidd#357]
I have update the system today. All things are updated. I edit the webcam.txt file. But it does not make any effect on the system. I disable the webcam but the webcam is still on. I change lot of things. but nothing happend. I disable the cam in text file. But I still got the steam on my screen. 
![Capture](https://user-images.githubusercontent.com/29024390/125045046-048dbe80-e0b6-11eb-9a31-a123b1ffcc82.JPG)
[webcamd.log](https://github.com/cadriel/fluidd/files/6789798/webcamd.log)
[fluidd-error.log](https://github.com/cadriel/fluidd/files/6789800/fluidd-error.log)
[fluidd-access.log](https://github.com/cadriel/fluidd/files/6789801/fluidd-access.log)
[webcam.txt](https://github.com/cadriel/fluidd/files/6789802/webcam.txt)
![cam](https://user-images.githubusercontent.com/29024390/125093229-8cda8680-e0eb-11eb-9e46-2282d0abf77c.JPG)

**Comment by cadriel** [comment]
For the first cam, if you don't want the stream - don't plug the cam in.

If you simply don't want the stream taking up your network bandwidth, then either collapse the camera panel in fluidd - or delete the camera in settings.

Otherwise this is working as intended. :)
