### ISSUE TITLE
Console all black in light mode

### ISSUE THREAD

**Issue by LazaroFilm** [cadriel/fluidd#4]
When in light mode, the console looks all black on black. 
![Screen Shot 2020-10-12 at 5 30 28 PM](https://user-images.githubusercontent.com/18351100/95792092-bf686780-0cb0-11eb-84c1-4118179a0f76.png)

**Comment by cadriel** [comment]
Thanks! Oversight on my part, I'll sort it out.

**Comment by cadriel** [comment]
this is resolved, will be in next release.
