### ISSUE TITLE
Core XY Z movement reversed 

### ISSUE THREAD

**Issue by arne182** [cadriel/fluidd#412]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when using a Core XY system and the Z + und Z - buttons move the axis in the opposite direction.

## Describe the solution you'd like:
Have the ability to swap the Z movement buttons.

## Describe alternatives you've considered:
Reverse the direction pin but that causes other problems

## Affected users and/or setups:
Core XY and others where the bed moves down instead of the extruder up

**Comment by LeandroMarceddu** [comment]
You mean this big button over here? 
![image](https://user-images.githubusercontent.com/227830/133114096-65d9285c-fe2a-46be-8a76-85f7d793d230.png)

**Comment by arne182** [comment]
Thanks
