### ISSUE TITLE
After trying to use [power] 

### ISSUE THREAD

**Issue by mmeulstee** [cadriel/fluidd#45]
Heya All,

How do you activate the "Power On/Off" widget??

**Comment by cadriel** [comment]
Power control is a plugin of Moonraker.
https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#power

**Comment by lalek54** [comment]
The gpiod module is missing in the fluiddpi image. Power plugin needs it even if you don t use gpio.  You can install it manually in the moonraker env. 
should it be possible to add it directly in the fluiddpi image?
