### ISSUE TITLE
[display_status] warning is always appear even there is [display]

### ISSUE THREAD

**Issue by n7484443** [cadriel/fluidd#46]
this warning always appear even there is [display] and display work.

its my [display] config
[display]
lcd_type: uc1701
cs_pin: z:P1.18
a0_pin: z:P1.19
encoder_pins: ^z:P3.25,^z:P3.26
click_pin: ^!z:P0.28
contrast: 63

**Comment by cadriel** [comment]
https://github.com/cadriel/fluidd/blob/develop/docs/printer-setup-and-macros.md

Please add the `[display_status]` block.
