### ISSUE TITLE
Delta Printer Friendly UI

### ISSUE THREAD

**Issue by gjudianto** [cadriel/fluidd#53]
Is it possible to change the axis home buttons that are friendlier for a delta printer? Home A, Home, B, Home C, Home All.

![image](https://user-images.githubusercontent.com/6621488/103107972-17e4ab00-45f8-11eb-8b11-a80089fceffa.png)

**Comment by cadriel** [comment]
Does it make sense to have the individual home buttons at all?

I.e., you can't home each axis on a delta with Klipper right? Would it not make sense to just have a single home button for the 3 rods., and then a single home button for Z?

Can you confirm that homing Z independently is still a thing on a delta configuration?

If so, perhaps it makes sense to just retain the two home buttons on the main panel and remove the individual home icons in the title for delta's.

**Comment by Hywelmartin** [comment]
no independent homing on deltas.. One button is enough... in the middle of the "cross"

**Comment by cadriel** [comment]
this will be in the next release! let me know if there are issues. Thanks!
