### ISSUE TITLE
FR: Able to select multiple files

### ISSUE THREAD

**Issue by edwardyeeks** [cadriel/fluidd#55]
Hey Cadriel,

Been using Fluidd faithfully ever since it first came out and it just only keeps getting better! One very small thing I found wanting was the ability to select multiple job files to perform a mass action (delete, move, etc.). Something like a checkbox next to each job file (and a select all?). It'll come in very handy in a print farm situation where file management becomes paramount.

Edward

**Comment by cadriel** [comment]
yep, this sounds like a good idea. I'll lump this in with a bunch of other file system related changes.
