### ISSUE TITLE
Overflow in tools card

### ISSUE THREAD

**Issue by davidsteinberger** [cadriel/fluidd#59]
I have quite some features of klipper enabled. That overlows the tool section.
<img width="714" alt="Screenshot 2020-12-31 at 01 28 54" src="https://user-images.githubusercontent.com/385430/103388172-dd9f7000-4b07-11eb-9fa7-950714e105b0.png">

Could we add some overflow here (can send a PR for that)?

**Comment by cadriel** [comment]
Yep. I was hoping people wouldn't need all of these things at the same time. I knew it'd become a problem 👍🏼 

I'll look into this, but likely I'll condense these buttons back into the hamburger I think.

**Comment by cadriel** [comment]
Ok - I've put a temporary fix in whereby the menu condenses to the hamburger at a higher breakpoint now. This will come in with the next release.

In a future update I'll likely move the home buttons out of here to alleviate this further.

Please re-open this bug if this doesn't fix the issue for you!

Thanks!

**Comment by davidsteinberger** [comment]
@cadriel Awesome, Thank You!
