### ISSUE TITLE
Add a way to configure the bed mesh parameters?

### ISSUE THREAD

**Issue by thiagosfsilva** [cadriel/fluidd#64]
Hi, just started using Fluidd, thank you for the great job! I noticed the Bed Mesh calibrate button runs a very fast mesh sampling routine, which may not be ideasl if the probe is not super accurate. Where could I go to change the bed mesh calibration  parameters for the button? Maybe these should be exposed to the user for UI config?

**Comment by cadriel** [comment]
This is directly in your klipper configuration for now;
https://www.klipper3d.org/Config_Reference.html#bed_mesh

We have plans to expose configuration in UI - but there's a lot of ground work that needs to happen first.
