### ISSUE TITLE
Gpiod module missing

### ISSUE THREAD

**Issue by lalek54** [cadriel/fluidd#66]
I try to use the [power] plugin of moonraker but gpiod module is missing. I managed to install it via pip in the moonraker environnement and everything is fine. 
bit should it be possible to add gpiod directly in the fluiddpi image?. It will be way easier to use [power] plugin.

**Comment by cadriel** [comment]
GPIOD is already installed on the base FluiddPI image.

Moonraker introduced virtual env changes not so long ago, so depending on how old your image was, might determine if those dependencies were installed or not.

I believe the -r flag when using the `install-moonraker.sh` script would install / update these by default also.
Example;
```
./scripts/install-moonraker.sh -r -f -c /home/pi/klipper_config/moonraker.conf
```

Looking at how moonraker installs this dep, i'm not sure using pip in its virtual env is the correct approach.
