### ISSUE TITLE
FR: Allow manual control of fan_generic type fans

### ISSUE THREAD

**Issue by dspears0809** [cadriel/fluidd#67]
Feature Request

The following klipper configuration allows "fan_generic" specified fans to appear in Fluidd, but they have no manual speed control slider.

[fan_generic ebay_fan_0]
pin: FAN_4
max_power: 1.0
kick_start_time: 0.5

[fan_generic ebay_fan_1]
pin: FAN_5
max_power: 1.0
kick_start_time: 0.5

Would like to see support for control of "fan_generic" specified fans.

**Comment by cadriel** [comment]
This should be fixed for the next release. Cheers!

**Comment by cadriel** [comment]
Oh, please let me know if this is working correctly. I can't test this as easily from here. If its not, feel free to re-open this issue.
