### ISSUE TITLE
Filament below 1m is reported as millimeters

### ISSUE THREAD

**Issue by top-gun** [cadriel/fluidd#70]
Hi, 

i noticed a unit mistake in the filament length. If a filament value is below 1m, the unit is wrongly displaxed as millimeters. 

The status in the screenshot shows a short printjob. Correct is: 0.44m / 0.77m.

Fluidd shows 0.44mm / 0.77mm which is wrong.

The same happens on the first 99cm of a printjob. Fluidd says 0.01mm up to 0.99mm, then 1.00m.

**Comment by top-gun** [comment]
![1252EF4E-41AF-4188-A6C5-C508B05BC19E](https://user-images.githubusercontent.com/3148118/103566565-7e07e280-4ec2-11eb-8e17-91caff67a0a8.png)

**Comment by cadriel** [comment]
Thanks for the report! I'll get this fixed for next release.
