### ISSUE TITLE
min_extrude_temp value of 0 causes display issues in the Tool tab

### ISSUE THREAD

**Issue by FHeilmann** [cadriel/fluidd#75]
my `min_extrude_temp` is 0, which causes this strange issue in the Tool tab:
![image](https://user-images.githubusercontent.com/4352664/103796306-52facb80-5047-11eb-9d8f-11f2ed6bf423.png)

**Comment by cadriel** [comment]
Klipper gets angry at me when I set `min_extrude_temp` to 0. I assume you're on an older version of klipper for that to work. In any case, there was an issue. I'm pretty good at forgetting `0 === false` 👍🏼 

Anyway, I think I've fixed it - will be in next release. If I missed something, please re-open the bug.

**Comment by FHeilmann** [comment]
I don't know why klipper gets angry at you. I'm on the latest version `v0.9.1-143` and I can set min_extrude_temp to 0 just fine. Thanks for fixing it :)
