### ISSUE TITLE
Ability to hide Temperature updates in console

### ISSUE THREAD

**Issue by sugar012** [cadriel/fluidd#82]
Recently Mainsail added it and i think it's a nice addiction.
Basically remove this:
![immagine](https://user-images.githubusercontent.com/53581505/103921109-5f982600-5112-11eb-9268-f274d5dd1b8e.png)

**Comment by cadriel** [comment]
Yep, will do. Thanks!

**Comment by oeijoenj** [comment]
great to know it will come. Thanks

**Comment by cadriel** [comment]
This is coming next release.
