### ISSUE TITLE
Software regression

### ISSUE THREAD

**Issue by myB0B** [cadriel/fluidd#83]
Please remove the rollout introduce with the 1.4.2 version
it's a pure software regression, and a nightmare to use

before : 
1 click to home

now : 
1 click to open rollout
another click to open rollout because i miss the button
another click to open because don't sure i click well and nothing is open
another click to open but in the mean time the rollout appear ! so it close....(
another click and finaly i can click the button 'all'  \o/

this is not possible...

rollout is usefull when IHM is missing place to show all stuff... but here the is enought room for buttons on computer screen and enougth place on smart device on the right of the cross buttons or any other place...

pleaaaaaase..

**Comment by cadriel** [comment]
these will be changing in the next release..
