### ISSUE TITLE
How to show percentage progress circle, thumbnail and also enclosure temp ?

### ISSUE THREAD

**Issue by oeijoenj** [cadriel/fluidd#84]
Hi all,

been browsing in closed issue and I see one can show right progress circle and also can see the thumbnail while mine is not.
Also I see that in target tab, can show enclosure temp, that will automatically show when I connect temp sensor?
Thanks so much

![image](https://user-images.githubusercontent.com/7046560/104005504-d0554600-51d7-11eb-8d69-acae7fdb5690.png)

**Comment by cadriel** [comment]
For support questions, please try the various discords;
https://discord.gg/GZ3D5tqfcF
