### ISSUE TITLE
OctoPrint-TPLinkSmartplug

### ISSUE THREAD

**Issue by Oranginator** [cadriel/fluidd#85]
Hi,

is it planned to develop an plugin like [https://github.com/jneilliii/OctoPrint-TPLinkSmartplug](url)? It brings a lot of safety against temperatrue runaways.

Best regards.

**Comment by cadriel** [comment]
TPLink SmartPlugs are already supported by way of moonrakers plugin's.
https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#power

Further support isn't planned other than what's already in place.
