### ISSUE TITLE
Separate manual move speed for Z

### ISSUE THREAD

**Issue by DerDominik** [cadriel/fluidd#87]
Hi there,

yesterday I tested Fluidd und it seems to look and work pretty good.
But it is possible to seperate the move speed for Z axis as F6000 is very fast and change the speed via the manual slider is not comfortable.

In my mind a change in utils.ts is necessary (line 419-421).
If axis = x or y --> F6000
If axis = z --> F720
Maybe it's quite good to make the speed configurable in the settings.

Or is there a way to do this what I haven't seen?

Thanks,
**DerDominik**

**Comment by cadriel** [comment]
This will be in the next release. :)
