### ISSUE TITLE
UI Suggestion for Ultra Wide Monitors

### ISSUE THREAD

**Issue by hickmanz** [cadriel/fluidd#9]
Low priority but on an ultra wide screen the UI looks stretched.  May be better to remove max-width from .container--fluid at a certain window width

![image](https://user-images.githubusercontent.com/20329886/96538495-43e15a00-125e-11eb-9b12-2e20a48b8f2e.png)
![image](https://user-images.githubusercontent.com/20329886/96538506-49d73b00-125e-11eb-80ac-e1dd8425da71.png)

**Comment by cadriel** [comment]
Yep, will take into consideration! Thanks.

**Comment by cadriel** [comment]
This has been implemented in v0.0.9! Thanks!
