### ISSUE TITLE
Add double click home action

### ISSUE THREAD

**Issue by noobydp** [cadriel/fluidd#92]
I keep finding myself clicking or double clicking the Home button (and I dont really like the hover over popup buttons).
Would you be able to add a double click action to the home button so double click homes all  axes?

Thanks :)

![image](https://user-images.githubusercontent.com/5045555/104306824-660b1100-5509-11eb-8094-a3ae67bcb4c2.png)

**Comment by cadriel** [comment]
You're on an old version of Fluidd. Have you enabled the built in update manager?

Please upgrade.

**Comment by noobydp** [comment]
Thanks!

I'm using the Kiuah install script and it doesnt look like it configured the update_manager section of moonraker.conf
I'll submit a request for them to add.
