### ISSUE TITLE
Replace online stylesheets with bundled one

### ISSUE THREAD

**Issue by expeditioneer** [cadriel/fluidd#93]
Currently there are referenced online stylesheets in the index.html 

- https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css
- https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900

It would be great when these could be replaced with bundled one. This could be integrated in the build process with something like https://www.npmjs.com/package/get-google-fonts.

The use case are printers or instances which have no internet connection.

**Comment by cadriel** [comment]
Oversight on my part, thanks for spotting. I'll get this sorted in an upcoming release.

**Comment by cadriel** [comment]
This will be in the next release. Thanks!
