### ISSUE TITLE
FR: Idle timeout indicator

### ISSUE THREAD

**Issue by series8217** [cadriel/fluidd#94]
Would be nice to see a visual indication when an idle timeout has occurred. Took me awhile to figure out why my enclosure pre-heating stopped.

I may look into implementing this --can Fluidd dump messages into the Console or are they generated by Klipper or Moonraker?

**Comment by cadriel** [comment]
It already does? The status panel will say 'Idle' when it has hit the idle timeout.

**Comment by cadriel** [comment]
![Screen Shot 2021-01-14 at 11 26 01 AM](https://user-images.githubusercontent.com/205520/104626282-54398300-565b-11eb-8553-2475b1142e2e.png)

For reference :)
