### ISSUE TITLE
New install missing cfg values "HERE" link doesn't goes to 404 page

### ISSUE THREAD

**Issue by tomohulk** [cadriel/fluidd#95]
Just installed this, its amazing and so much faster then octoprint, thanks for your efforts!  The message box that pops up with a new install has a `Configuration options can be found *here*` hyperlink that goes to a 404 page, not sure where it should be pointing to.  I was able to locate all I needed to get up and running in the docs.  just an FYI.  thanks!

**Comment by cadriel** [comment]
Yep, known. Will be fixed in next release. Thanks!
