### ISSUE TITLE
Change dashboard title order

### ISSUE THREAD

**Issue by ChipCE** [cadriel/fluidd#99]
Hi,
Sorry for my skeptic but I think we should change the dashboard title order. When printing the page title will be something like <code>[%12] | Dashboard | PrinterName</code> but due to the length limit of the tab in browser it can only display  <code>[%12] | Dashboard | Pri</code>. There will be no problem with just one printer, but for more than one it's hard to tell what tab is what printer dashboard by the tab name. 

![title](https://user-images.githubusercontent.com/22391265/104830680-463a6b00-58c4-11eb-87be-ebdd1304f054.png)

**Comment by cadriel** [comment]
These are now swapped, look for it in the next release! :)
